# Generated by Django 4.1.13 on 2024-05-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
